-- Add all social categories (original 10 + new 27 = 37 total)
INSERT INTO social_categories (name, slug, description, icon, color, display_order) VALUES
    ('AI Content', 'ai-content', 'AI-generated content and technology discussions', '🤖', 'from-violet-400 to-indigo-500', 1),
    ('Animation', 'animation', 'Halal animated content and cartoons', '🎬', 'from-fuchsia-400 to-pink-500', 2),
    ('Art', 'art', 'Islamic art, calligraphy, and creative expressions', '🎨', 'from-rose-400 to-pink-500', 3),
    ('Astrology', 'astrology', 'Islamic perspectives on stars and celestial guidance', '✨', 'from-indigo-400 to-violet-500', 4),
    ('Beauty', 'beauty', 'Beauty tips, tutorials, and product reviews', '💄', 'from-purple-400 to-pink-500', 5),
    ('Couples', 'couples', 'Marriage tips and relationship advice', '💑', 'from-rose-400 to-pink-500', 6),
    ('Crypto', 'crypto', 'Cryptocurrency education and halal investing', '₿', 'from-amber-400 to-yellow-500', 7),
    ('Elders', 'elders', 'Wisdom and guidance from community elders', '👴', 'from-stone-400 to-amber-600', 8),
    ('Family Planning', 'family-planning', 'Guidance on family planning and parenting', '👨‍👩‍👧‍👦', 'from-teal-400 to-emerald-500', 9),
    ('Fashion', 'fashion', 'Modest fashion inspiration and styling', '👗', 'from-amber-400 to-orange-500', 10),
    ('Fatherhood', 'fatherhood', 'Parenting guidance and advice for fathers', '👨‍👧', 'from-blue-400 to-indigo-500', 11),
    ('Gaming', 'gaming', 'Halal gaming content and reviews', '🎮', 'from-purple-400 to-fuchsia-500', 12),
    ('History', 'history', 'Islamic history and historical narratives', '📜', 'from-amber-500 to-yellow-600', 13),
    ('Humor', 'humor', 'Halal humor and light-hearted content', '😄', 'from-yellow-400 to-amber-500', 14),
    ('Husbands Realm', 'husbands-realm', 'Content and discussions for husbands', '👨', 'from-slate-400 to-zinc-500', 15),
    ('Islam', 'islam', 'Islamic reminders, lectures, and discussions', '🕌', 'from-emerald-400 to-teal-500', 16),
    ('Learn Arabic', 'learn-arabic', 'Arabic language lessons and resources', '📝', 'from-emerald-400 to-green-500', 17),
    ('Mens Corner', 'mens-corner', 'Discussions and content for brothers', '👨', 'from-blue-400 to-indigo-500', 18),
    ('Mosques', 'mosques', 'Mosque tours, reviews, and Islamic architecture', '🕌', 'from-emerald-500 to-teal-600', 19),
    ('Motherhood', 'motherhood', 'Parenting guidance and advice for mothers', '👩‍👧', 'from-pink-400 to-rose-500', 20),
    ('Music', 'music', 'Halal music, nasheeds, and vocal performances', '🎵', 'from-violet-400 to-purple-500', 21),
    ('Nature', 'nature', 'Natural beauty and reflections on creation', '🌿', 'from-green-400 to-emerald-500', 22),
    ('News', 'news', 'Muslim community news and updates', '📰', 'from-teal-400 to-cyan-600', 23),
    ('Politics', 'politics', 'Islamic perspectives on current affairs', '🏛️', 'from-indigo-400 to-blue-600', 24),
    ('Prayers', 'prayers', 'Prayer guides, du''as, and spiritual practices', '🤲', 'from-cyan-400 to-blue-500', 25),
    ('Quran', 'quran', 'Quran recitations, tafsir, and learning', '📖', 'from-cyan-400 to-blue-500', 26),
    ('Recipe', 'recipe', 'Halal recipes and cooking tutorials', '🍽️', 'from-green-400 to-emerald-500', 27),
    ('Science', 'science', 'Scientific discoveries and Islamic perspectives', '🔬', 'from-cyan-400 to-blue-500', 28),
    ('Series', 'series', 'Islamic educational series and episodic content', '📺', 'from-sky-400 to-blue-500', 29),
    ('Skit', 'skit', 'Halal comedy skits and short-form content', '🎭', 'from-orange-400 to-red-500', 30),
    ('Sports', 'sports', 'Islamic sports content and halal athletics', '⚽', 'from-lime-400 to-green-500', 31),
    ('Tech', 'tech', 'Technology reviews, tutorials, and discussions', '💻', 'from-slate-400 to-gray-500', 32),
    ('Trading', 'trading', 'Stock market, forex, and halal trading strategies', '📈', 'from-green-400 to-lime-500', 33),
    ('Travel', 'travel', 'Islamic travel destinations and experiences', '✈️', 'from-sky-400 to-cyan-500', 34),
    ('Wedding Planning', 'wedding-planning', 'Islamic wedding planning and marriage preparation', '💍', 'from-rose-400 to-pink-600', 35),
    ('Wives World', 'wives-world', 'Content and discussions for wives', '👩', 'from-rose-400 to-pink-500', 36),
    ('Women Only', 'women-only', 'A safe space for women to share and connect', '👩', 'from-pink-400 to-rose-500', 37)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    icon = EXCLUDED.icon,
    color = EXCLUDED.color,
    display_order = EXCLUDED.display_order;
