#!/usr/bin/env tsx
/**
 * Generate and encrypt Admin & Community Bitcoin private keys
 * 
 * Usage:
 *   tsx scripts/generate-bitcoin-keys.ts              # Uses NODE_ENV from .env.local
 *   NODE_ENV=production tsx scripts/generate-bitcoin-keys.ts  # Force mainnet
 *   NODE_ENV=development tsx scripts/generate-bitcoin-keys.ts # Force testnet
 * 
 * This will output:
 * - NEW ENCRYPTION KEY (256-bit, for encrypting/decrypting all Bitcoin private keys)
 * - Generated Bitcoin private keys (WIF format)
 * - Encrypted private keys (encrypted with the NEW ENCRYPTION KEY)
 * - Bitcoin addresses
 * 
 * The NEW ENCRYPTION KEY will be used to encrypt/decrypt:
 * - Admin master Bitcoin private key
 * - Community Bitcoin private key
 * - User Bitcoin private keys (generated during email verification)
 * - Mahr wallet private keys (male users)
 * - Purse wallet private keys (female users)
 * 
 * Copy the encrypted keys to:
 * - .env.local: ENCRYPTION_KEY (the NEW key generated by this script)
 * - .env.local: ADMIN_MASTER_PRIVATE_KEY_ENCRYPTED
 * - .env.local: COMMUNITY_PRIVATE_KEY_ENCRYPTED
 * - Database admin_settings: admin_master_private_key_encrypted
 * - Database admin_settings: community_private_key_encrypted
 * - Database users: btc_private_key_encrypted (for each user)
 * 
 * ⚠️  NETWORK SELECTION:
 * - NODE_ENV=development → Testnet (addresses start with 'tb1')
 * - NODE_ENV=production  → Mainnet (addresses start with 'bc1')
 * 
 * ⚠️  CRITICAL:
 * - The ENCRYPTION KEY must be kept secure and backed up
 * - If lost, all encrypted Bitcoin private keys are permanently inaccessible
 * - All Bitcoin private keys are encrypted with this single key
 */

import * as dotenv from 'dotenv'
import * as crypto from 'crypto'
import { generateUserKeypair } from '../lib/bitcoin-split'
import { encrypt, decrypt } from '../lib/encryption'

// Load environment variables
dotenv.config({ path: '.env.local' })

// Generate new encryption key (256-bit / 32 bytes = 64 hex characters)
const newEncryptionKey = crypto.randomBytes(32).toString('hex')

// Determine network
const network = process.env.NODE_ENV === 'production' ? 'MAINNET' : 'TESTNET'
const networkWarning = network === 'MAINNET' 
  ? '🚨 REAL BITCOIN - USE WITH CAUTION!'
  : '🧪 Test Bitcoin - Safe for testing'

console.log(`🔐 Bitcoin Key Generator for Admin & Community Wallets`)
console.log(`🌐 Network: ${network} ${networkWarning}\n`)
console.log('=' .repeat(80))

// Display new encryption key
console.log('\n🔑 NEW ENCRYPTION KEY GENERATED:')
console.log('=' .repeat(80))
console.log(`\nENCRYPTION_KEY=${newEncryptionKey}\n`)
console.log('=' .repeat(80))
console.log('⚠️  IMPORTANT: Update your .env.local with this new key!')
console.log('⚠️  All existing encrypted data will need to be re-encrypted with the new key!')
console.log('=' .repeat(80))

// Generate Admin Master Key (index 0)
console.log('\n📋 Generating ADMIN MASTER KEY (index 0)...')
const adminKeys = generateUserKeypair(0)

console.log('\n✅ Admin Key Generated:')
console.log('-'.repeat(80))
console.log(`Address:           ${adminKeys.address}`)
console.log(`Private Key (WIF): ${adminKeys.privateKeyEncrypted}`)
console.log(`Public Key:        ${adminKeys.publicKey}`)

// Encrypt the private key with the NEW encryption key
const adminEncryptedKey = encrypt(adminKeys.privateKeyEncrypted, newEncryptionKey)
console.log(`Encrypted Key:     ${adminEncryptedKey}`)
console.log('-'.repeat(80))

// Generate Community Key (index 1)
console.log('\n📋 Generating COMMUNITY KEY (index 1)...')
const communityKeys = generateUserKeypair(1)

console.log('\n✅ Community Key Generated:')
console.log('-'.repeat(80))
console.log(`Address:           ${communityKeys.address}`)
console.log(`Private Key (WIF): ${communityKeys.privateKeyEncrypted}`)
console.log(`Public Key:        ${communityKeys.publicKey}`)

// Encrypt the private key with the NEW encryption key
const communityEncryptedKey = encrypt(communityKeys.privateKeyEncrypted, newEncryptionKey)
console.log(`Encrypted Key:     ${communityEncryptedKey}`)
console.log('-'.repeat(80))

// Display .env.local updates
console.log('\n📝 Update your .env.local file with these values:')
console.log('=' .repeat(80))
console.log(`\nENCRYPTION_KEY=${newEncryptionKey}`)
console.log(`ADMIN_MASTER_PRIVATE_KEY_ENCRYPTED=${adminEncryptedKey}`)
console.log(`COMMUNITY_PRIVATE_KEY_ENCRYPTED=${communityEncryptedKey}`)
console.log('\n' + '=' .repeat(80))

// Display database update SQL
console.log('\n📝 Update your database admin_settings table:')
console.log('=' .repeat(80))
console.log(`\nUPDATE admin_settings SET`)
console.log(`  admin_master_private_key_encrypted = '${adminEncryptedKey}',`)
console.log(`  community_private_key_encrypted = '${communityEncryptedKey}',`)
console.log(`  admin_payout_address = 'BC1QMV3U6WHG45ATGU9W525ZGJTQPWVS4VKM77T9C4'`)
console.log(`WHERE id = (SELECT id FROM admin_settings LIMIT 1);`)
console.log('\n' + '=' .repeat(80))

// Security warning
console.log('\n⚠️  SECURITY WARNINGS:')
console.log('=' .repeat(80))
console.log('1. Save the private keys shown above in a secure location!')
console.log('2. These private keys control the Bitcoin funds.')
console.log('3. Never share the unencrypted private keys.')
console.log('4. Only the ENCRYPTED keys should be stored in the database.')
console.log('5. 🚨 CRITICAL: Keep your ENCRYPTION_KEY secure (.env.local)!')
console.log('6. If ENCRYPTION_KEY is lost, all encrypted data is permanently inaccessible!')
console.log('7. Back up the private keys offline (paper wallet, hardware wallet).')
console.log('8. Store ENCRYPTION_KEY in a secure password manager or hardware security module.')

if (network === 'MAINNET') {
  console.log('9. 🚨 THIS IS MAINNET - REAL BITCOIN WITH REAL VALUE!')
  console.log('10. Double-check addresses before sending funds.')
  console.log('11. Start with a small test transaction first.')
  console.log('12. Consider using a hardware wallet for extra security.')
} else {
  console.log('9. This is TESTNET - use testnet faucets to get test BTC.')
  console.log('10. Faucet: https://testnet-faucet.mempool.co/')
  console.log('11. Test thoroughly before switching to mainnet!')
}

console.log('=' .repeat(80))

// Test decryption with the NEW encryption key
console.log('\n🧪 Testing encryption/decryption with NEW key...')
const adminDecrypted = decrypt(adminEncryptedKey, newEncryptionKey)
const communityDecrypted = decrypt(communityEncryptedKey, newEncryptionKey)

if (adminDecrypted === adminKeys.privateKeyEncrypted && communityDecrypted === communityKeys.privateKeyEncrypted) {
  console.log('✅ Encryption/decryption test passed!')
  console.log('✅ Keys can be successfully decrypted with the NEW ENCRYPTION_KEY')
  console.log('✅ You can now safely update your .env.local with the new key')
} else {
  console.log('❌ Encryption/decryption test failed!')
  console.log('❌ DO NOT use this key - there was an error')
  process.exit(1)
}

console.log('\n✅ Key generation complete!\n')
